[windows]
installs = false

[windows.links]
config = "~\\AppData\\Roaming\\espanso\\config"
match = "~\\AppData\\Roaming\\espanso\\match"

["linux|darwin"]
installs = false

["linux|darwin".links]
config = "~/.config/espanso/config"
match = "~/.config/espanso/match"
