[windows]
# cmd = """
# Set-ExecutionPolicy RemoteSigned -Scope CurrentUser
# irm get.scoop.sh | iex
# """
installs = "Set-ExecutionPolicy RemoteSigned -Scope CurrentUser && irm get.scoop.sh | iex"

["linux|darwin"]
installs = false
